#!/bin/bash

if [ -f ".env.default" ]
then
  export $(cat .env.default | sed 's/#.*//g' | xargs)
fi

if [ -f ".env" ]
then
  export $(cat .env | sed 's/#.*//g' | xargs)
fi

BINARY_PATH="${PWD}/../server/bin/neko"

# use -r to rebuild
if [ ! -f "${BINARY_PATH}" ] || [ "$1" == "-r" ]; then
  ./rebuild-server
fi

# if image starts with nvidia- add --gpus all
if [[ "${SERVER_TAG}" == "nvidia-"* ]]; then
  GPU_FLAG="--gpus all"
  echo "Nvidia GPU acceleration enabled"
fi

# if image starts with intel- add --device /dev/dri
if [[ "${SERVER_TAG}" == "intel-"* ]]; then
  GPU_FLAG="--device /dev/dri"
  echo "Intel GPU acceleration enabled"
fi

# use --gpus all to enable GPU acceleration
docker run -d \
  --privileged \
  --name "neko_dev" \
  $GPU_FLAG \
  -p "${SERVER_PORT}:8080" \
  -p "${SERVER_EPR}:${SERVER_EPR}/udp" \
  -e "NEKO_SCREEN=1920x1080@60" \
  -e "NEKO_EPR=${SERVER_EPR}" \
  -e "NEKO_NAT1TO1=${SERVER_IP}" \
  -e "NEKO_ICELITE=true" \
  -e "NEKO_MAX_FPS=100" \
  -e NVIDIA_VISIBLE_DEVICES=all \
  -e NVIDIA_DRIVER_CAPABILITIES=all \
  -v "${BINARY_PATH}:/usr/bin/neko" \
  -v /home/git/neko/.docker/base/xorg.conf:/etc/neko/xorg.conf \
  -v /home/git/neko/.docker/base/supervisord.conf:/etc/neko/supervisord.conf \
  -v /home/git/neko/.docker/google-chrome/supervisord.nvidia.conf:/etc/neko/supervisord/google-chrome.conf \
  --mount type=bind,source=/usr/lib64/xorg,target=/usr/lib64/xorg \
  --shm-size=8G \
  --cap-add SYS_ADMIN \
  --add-host admin.xc.com:192.168.0.14 \
  --add-host 3d.xc.com:192.168.0.14 \
  ${BUILD_IMAGE}:${SERVER_TAG}